var info = {
    lang: "sn",
    version: "bdsc",
    books: [
        { name: "Genesisi", synonyms: ["Gen"], numChapters: 50 },
        { name: "Ekisodho", synonyms: ["Exod"], numChapters: 40 },
        { name: "Revhitiko", synonyms: ["Lev"], numChapters: 27 },
        { name: "Numeri", synonyms: ["Num"], numChapters: 36 },
        { name: "Dhuteronomi", synonyms: ["Deut"], numChapters: 34 },
        { name: "Joshua", synonyms: ["Josh"], numChapters: 24 },
        { name: "Vatongi", synonyms: ["Judg"], numChapters: 21 },
        { name: "Rute", synonyms: ["Ruth"], numChapters: 4 },
        { name: "1 Samueri", synonyms: ["1Sam"], numChapters: 31 },
        { name: "2 Samueri", synonyms: ["2Sam"], numChapters: 24 },
        { name: "1 Madzimambo", synonyms: ["1Kgs"], numChapters: 22 },
        { name: "2 Madzimambo", synonyms: ["2Kgs"], numChapters: 25 },
        { name: "1 Makoronike", synonyms: ["1Chr"], numChapters: 29 },
        { name: "2 Makoronike", synonyms: ["2Chr"], numChapters: 36 },
        { name: "Ezira", synonyms: ["Ezra"], numChapters: 10 },
        { name: "Nehemia", synonyms: ["Neh"], numChapters: 13 },
        { name: "Esteri", synonyms: ["Esth"], numChapters: 10 },
        { name: "Jobho", synonyms: ["Job"], numChapters: 42 },
        { name: "Mapisarema", synonyms: ["Ps"], numChapters: 150 },
        { name: "Zvirevo", synonyms: ["Prov"], numChapters: 31 },
        { name: "Muparidzi", synonyms: ["Eccl"], numChapters: 12 },
        { name: "Rwiyo Rukuru rwaSoromoni", synonyms: ["Song"], numChapters: 8 },
        { name: "Isaya", synonyms: ["Isa"], numChapters: 66 },
        { name: "Jeremia", synonyms: ["Jer"], numChapters: 52 },
        { name: "Kuungudza kwaJeremia", synonyms: ["Lam"], numChapters: 5 },
        { name: "Ezekieri", synonyms: ["Ezek"], numChapters: 48 },
        { name: "Dhanieri", synonyms: ["Dan"], numChapters: 12 },
        { name: "Hosea", synonyms: ["Hos"], numChapters: 14 },
        { name: "Joere", synonyms: ["Joel"], numChapters: 3 },
        { name: "Amosi", synonyms: ["Amos"], numChapters: 9 },
        { name: "Obhadhia", synonyms: ["Obad"], numChapters: 1 },
        { name: "Jona", synonyms: ["Jonah"], numChapters: 4 },
        { name: "Mika", synonyms: ["Mic"], numChapters: 7 },
        { name: "Nahumi", synonyms: ["Nah"], numChapters: 3 },
        { name: "Habhakuki", synonyms: ["Hab"], numChapters: 3 },
        { name: "Zefania", synonyms: ["Zeph"], numChapters: 3 },
        { name: "Hagai", synonyms: ["Hag"], numChapters: 2 },
        { name: "Zekaria", synonyms: ["Zech"], numChapters: 14 },
        { name: "Maraki", synonyms: ["Mal"], numChapters: 4 },
        { name: "Mateo", synonyms: ["Matt"], numChapters: 28 },
        { name: "Mako", synonyms: ["Mark"], numChapters: 16 },
        { name: "Ruka", synonyms: ["Luke"], numChapters: 24 },
        { name: "Johani", synonyms: ["John"], numChapters: 21 },
        { name: "Mabasa", synonyms: ["Acts"], numChapters: 28 },
        { name: "VaRoma", synonyms: ["Rom"], numChapters: 16 },
        { name: "1 VaKorinde", synonyms: ["1Cor"], numChapters: 16 },
        { name: "2 VaKorinde", synonyms: ["2Cor"], numChapters: 13 },
        { name: "VaGaratia", synonyms: ["Gal"], numChapters: 6 },
        { name: "VaEfeso", synonyms: ["Eph"], numChapters: 6 },
        { name: "VaFiripi", synonyms: ["Phil"], numChapters: 4 },
        { name: "VaKorose", synonyms: ["Col"], numChapters: 4 },
        { name: "1 VaTesaronika", synonyms: ["1Thess"], numChapters: 5 },
        { name: "2 VaTesaronika", synonyms: ["2Thess"], numChapters: 3 },
        { name: "1 Timoti", synonyms: ["1Tim"], numChapters: 6 },
        { name: "2 Timoti", synonyms: ["2Tim"], numChapters: 4 },
        { name: "Tito", synonyms: ["Titus"], numChapters: 3 },
        { name: "Firimoni", synonyms: ["Phlm"], numChapters: 1 },
        { name: "VaHebheru", synonyms: ["Heb"], numChapters: 13 },
        { name: "Jakobho", synonyms: ["Jas"], numChapters: 5 },
        { name: "1 Petro", synonyms: ["1Pet"], numChapters: 5 },
        { name: "2 Petro", synonyms: ["2Pet"], numChapters: 3 },
        { name: "1 Johani", synonyms: ["1John"], numChapters: 5 },
        { name: "2 Johani", synonyms: ["2John"], numChapters: 1 },
        { name: "3 Johani", synonyms: ["3John"], numChapters: 1 },
        { name: "Judha", synonyms: ["Jude"], numChapters: 1 },
        { name: "Zvakazarurwa", synonyms: ["Rev"], numChapters: 22 }
    ]
};

module.exports = info;
